<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * FACT-* — the append-only fact tables of the analytics star schema
     * (docs/30-data-model/01-analytics-model.md §4).
     *
     * Engine rules (ADR-0010 amended by ADR-0013 — Neon Postgres):
     *  - native declarative RANGE partitioning by date_key (no TimescaleDB
     *    hypertables; Neon supports neither the extension nor pg_cron);
     *  - APPEND-ONLY, enforced by a row trigger (partition detach/drop for
     *    retention bypasses row triggers by design);
     *  - every measure is tier-aware (DP-001): PUBLIC measures live in
     *    dedicated columns whose tier is fixed by the catalog; ESTIMATED
     *    measures (estimated_reach, emv) carry an explicit *_tier column so
     *    an estimate can never silently read as fact.
     *
     * Grains (canonical — never mixed):
     *  - fact_content_metric: one ContentItem per metric-snapshot bucket;
     *  - fact_creator_account: one PlatformAccount per account snapshot;
     *  - fact_mention: one detected Mention, stamped with the linked
     *    content's latest metrics;
     *  - fact_shipment: one Shipment (P3 loader — ENT-Shipment ships in P3);
     *  - fact_seeding_content: one Shipment × resulting ContentItem per
     *    snapshot bucket (P3 loader).
     *
     * Raw Blueprint cannot declare partitioned tables, so DDL is literal SQL.
     */
    private const FACT_TABLES = [
        'fact_content_metric' => <<<'SQL'
            CREATE TABLE fact_content_metric (
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                date_key date NOT NULL,
                metric_snapshot_id bigint NOT NULL,
                content_item_id bigint NOT NULL,
                platform_account_id bigint NOT NULL,
                creator_id bigint NULL,
                brand_id bigint NULL,
                platform text NOT NULL,
                content_type text NOT NULL,
                published_at timestamptz NULL,
                captured_at timestamptz NOT NULL,
                views numeric NULL,
                plays numeric NULL,
                likes numeric NULL,
                comments numeric NULL,
                shares numeric NULL,
                saves numeric NULL,
                metric_tier text NOT NULL DEFAULT 'PUBLIC',
                PRIMARY KEY (id, date_key),
                UNIQUE (metric_snapshot_id, date_key)
            ) PARTITION BY RANGE (date_key)
        SQL,
        'fact_creator_account' => <<<'SQL'
            CREATE TABLE fact_creator_account (
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                date_key date NOT NULL,
                metric_snapshot_id bigint NOT NULL,
                platform_account_id bigint NOT NULL,
                creator_id bigint NULL,
                platform text NOT NULL,
                captured_at timestamptz NOT NULL,
                followers numeric NULL,
                following numeric NULL,
                total_posts numeric NULL,
                follower_growth numeric NULL,
                avg_views numeric NULL,
                engagement_rate numeric NULL,
                posting_frequency numeric NULL,
                PRIMARY KEY (id, date_key),
                UNIQUE (metric_snapshot_id, date_key)
            ) PARTITION BY RANGE (date_key)
        SQL,
        'fact_mention' => <<<'SQL'
            CREATE TABLE fact_mention (
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                date_key date NOT NULL,
                mention_id bigint NOT NULL,
                monitored_subject_id bigint NOT NULL,
                content_item_id bigint NULL,
                story_id bigint NULL,
                creator_id bigint NULL,
                brand_id bigint NULL,
                product_id bigint NULL,
                campaign_id bigint NULL,
                platform text NULL,
                content_type text NULL,
                mention_type text NOT NULL,
                sentiment text NULL,
                detected_at timestamptz NOT NULL,
                mention_count integer NOT NULL DEFAULT 1,
                views numeric NULL,
                likes numeric NULL,
                comments numeric NULL,
                shares numeric NULL,
                saves numeric NULL,
                estimated_reach numeric NULL,
                estimated_reach_tier text NULL,
                emv numeric NULL,
                emv_tier text NULL,
                emv_currency character(3) NULL,
                PRIMARY KEY (id, date_key),
                UNIQUE (mention_id, date_key)
            ) PARTITION BY RANGE (date_key)
        SQL,
        'fact_shipment' => <<<'SQL'
            CREATE TABLE fact_shipment (
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                date_key date NOT NULL,
                shipment_id bigint NOT NULL,
                creator_id bigint NOT NULL,
                product_id bigint NOT NULL,
                brand_id bigint NULL,
                client_id bigint NULL,
                seeding_campaign_id bigint NOT NULL,
                campaign_id bigint NULL,
                shipped integer NOT NULL DEFAULT 1,
                posted integer NOT NULL DEFAULT 0,
                quantity numeric NULL,
                product_value numeric NULL,
                days_to_post numeric NULL,
                PRIMARY KEY (id, date_key),
                UNIQUE (shipment_id, date_key)
            ) PARTITION BY RANGE (date_key)
        SQL,
        'fact_seeding_content' => <<<'SQL'
            CREATE TABLE fact_seeding_content (
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                date_key date NOT NULL,
                shipment_id bigint NOT NULL,
                content_item_id bigint NOT NULL,
                metric_snapshot_id bigint NOT NULL,
                creator_id bigint NULL,
                product_id bigint NOT NULL,
                brand_id bigint NULL,
                client_id bigint NULL,
                seeding_campaign_id bigint NOT NULL,
                campaign_id bigint NULL,
                platform text NOT NULL,
                content_type text NOT NULL,
                content_count integer NOT NULL DEFAULT 1,
                views numeric NULL,
                likes numeric NULL,
                comments numeric NULL,
                shares numeric NULL,
                saves numeric NULL,
                estimated_reach numeric NULL,
                estimated_reach_tier text NULL,
                emv numeric NULL,
                emv_tier text NULL,
                PRIMARY KEY (id, date_key),
                UNIQUE (shipment_id, content_item_id, metric_snapshot_id, date_key)
            ) PARTITION BY RANGE (date_key)
        SQL,
    ];

    /** Yearly partitions; widen by adding partitions, retention drops old ones. */
    private const PARTITION_YEARS_FROM = 2024;

    private const PARTITION_YEARS_TO = 2032;

    public function up(): void
    {
        foreach (self::FACT_TABLES as $tableName => $ddl) {
            DB::statement($ddl);

            for ($year = self::PARTITION_YEARS_FROM; $year <= self::PARTITION_YEARS_TO; $year++) {
                $next = $year + 1;
                DB::statement(<<<SQL
                    CREATE TABLE {$tableName}_y{$year} PARTITION OF {$tableName}
                        FOR VALUES FROM ('{$year}-01-01') TO ('{$next}-01-01')
                SQL);
            }

            DB::statement("CREATE TABLE {$tableName}_default PARTITION OF {$tableName} DEFAULT");
        }

        // Slice indexes for rollup construction.
        DB::statement('CREATE INDEX fact_content_metric_content_index ON fact_content_metric (content_item_id, captured_at)');
        DB::statement('CREATE INDEX fact_content_metric_creator_index ON fact_content_metric (creator_id, date_key)');
        DB::statement('CREATE INDEX fact_creator_account_account_index ON fact_creator_account (platform_account_id, captured_at)');
        DB::statement('CREATE INDEX fact_creator_account_creator_index ON fact_creator_account (creator_id, date_key)');
        DB::statement('CREATE INDEX fact_mention_brand_index ON fact_mention (brand_id, date_key)');
        DB::statement('CREATE INDEX fact_mention_creator_index ON fact_mention (creator_id, date_key)');
        DB::statement('CREATE INDEX fact_shipment_product_index ON fact_shipment (product_id, date_key)');
        DB::statement('CREATE INDEX fact_seeding_content_product_index ON fact_seeding_content (product_id, date_key)');

        // Append-only enforcement (facts are written once, never mutated).
        DB::unprepared(<<<'SQL'
            CREATE OR REPLACE FUNCTION qds_analytics_append_only() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'analytics facts are append-only: % on % is not permitted (ADR-0010)', TG_OP, TG_TABLE_NAME;
            END;
            $$ LANGUAGE plpgsql;
        SQL);

        // Extracts one labelled PUBLIC MetricValue amount from a metrics
        // envelope list (DP-001: only PUBLIC-tier values feed PUBLIC fact
        // measures; other tiers never silently enter an observed column).
        DB::unprepared(<<<'SQL'
            CREATE OR REPLACE FUNCTION qds_public_metric(metrics jsonb, name text) RETURNS numeric
            LANGUAGE sql IMMUTABLE STRICT AS $$
                SELECT (m->>'amount')::numeric
                FROM jsonb_array_elements(metrics) m
                WHERE m->>'metric' = name AND m->>'tier' = 'PUBLIC'
                LIMIT 1
            $$;
        SQL);

        foreach (array_keys(self::FACT_TABLES) as $tableName) {
            DB::unprepared(<<<SQL
                CREATE TRIGGER {$tableName}_append_only
                    BEFORE UPDATE OR DELETE ON {$tableName}
                    FOR EACH ROW EXECUTE FUNCTION qds_analytics_append_only();
            SQL);
        }

        // Loader high-water marks + refresh telemetry (operational tables
        // for SVC-Analytics — same flagged-deviation class as the ingestion
        // operational tables; not canonical ENT-*).
        Schema::create('analytics_watermarks', function ($table) {
            $table->string('source', 60)->primary();
            $table->unsignedBigInteger('last_id')->default(0);
            $table->timestamp('updated_at');
        });

        Schema::create('analytics_refreshes', function ($table) {
            $table->id();
            $table->string('status', 10);
            $table->unsignedInteger('rollups_refreshed')->default(0);
            $table->jsonb('facts_loaded')->nullable();
            $table->text('error')->nullable();
            $table->timestamp('started_at');
            $table->timestamp('finished_at')->nullable();

            $table->index('started_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('analytics_refreshes');
        Schema::dropIfExists('analytics_watermarks');

        foreach (array_keys(self::FACT_TABLES) as $tableName) {
            DB::statement("DROP TABLE IF EXISTS {$tableName} CASCADE");
        }

        DB::unprepared('DROP FUNCTION IF EXISTS qds_analytics_append_only()');
        DB::unprepared('DROP FUNCTION IF EXISTS qds_public_metric(jsonb, text)');
    }
};
